INSERT INTO receta (codigo, nombre, descripcion, precio, categoria) VALUES
('GAL001', 'Galleta de Chips de Chocolate', 'Galleta artesanal con chips de chocolate semiamargo.', 1800, 'galletas'),
('GAL002', 'Galleta de Avena y Miel', 'Galleta crocante de avena con toque de miel natural.', 1600, 'galletas'),
('GAL003', 'Galleta Red Velvet', 'Galleta suave sabor red velvet con relleno de queso crema.', 2200, 'galletas'),
('GAL004', 'Porogalleta', 'Galleta inspirada en los poros de League of Legends, rellena con crema de vainilla y chips de chocolate blanco.', 2800, 'galletas'),
('MUF001', 'Muffin de Arándanos', 'Muffin esponjoso con arándanos frescos y vainilla.', 2500, 'muffin'),
('MUF002', 'Muffin de Chocolate', 'Muffin húmedo con cacao y chips de chocolate.', 2400, 'muffin'),
('MUF003', 'Muffin de Banana y Nuez', 'Muffin casero de banana madura con nueces trozadas.', 2600, 'muffin'),
('ALF001', 'Alfajor de Maizena', 'Alfajor de maicena relleno con dulce de leche y coco.', 1500, 'alfajores'),
('ALF002', 'Alfajor de Chocolate Blanco', 'Alfajor bañado en chocolate blanco con relleno de manjar.', 1900, 'alfajores'),
('ALF003', 'Alfajor Triple Chocolate', 'Alfajor triple relleno de mousse de chocolate.', 2300, 'alfajores'),
('PAS001', 'Pastel de Chocolate', 'Pastel húmedo de chocolate con cobertura ganache.', 18500, 'pasteles'),
('PAS002', 'Cheesecake de Frutilla', 'Cheesecake cremoso con salsa de frutillas naturales.', 21000, 'pasteles'),
('PAS003', 'Torta Tres Leches', 'Bizcocho suave remojado en mezcla de tres leches.', 19500, 'pasteles'),
('PAS004', 'Pastel Red Velvet', 'Pastel rojo aterciopelado con relleno de queso crema.', 22000, 'pasteles'),
('PAS005', 'Torta Selva Negra', 'Pastel de chocolate con crema y cerezas.', 24000, 'pasteles'),
('PAS006', 'Pastel de Zanahoria', 'Pastel húmedo de zanahoria con frosting de queso crema.', 20000, 'pasteles'),
('PAS007', 'Torta Mil Hojas', 'Pastel tradicional de capas hojaldradas con manjar.', 26000, 'pasteles'),
('PAS008', 'Pastel de Limón', 'Pastel cítrico con relleno suave de crema de limón.', 19500, 'pasteles'),
('PAS009', 'Torta Oreo', 'Pastel de vainilla y chocolate con galletas Oreo trituradas.', 23000, 'pasteles');